// Generated by dia2code
#ifndef SERVER__SERVER__H
#define SERVER__SERVER__H


namespace server {
  class ServicesManager;
}

#include "ServicesManager.h"

namespace server {

  /// class Server - 
  class Server {
    // Associations
    // Attributes
  public:
    ServicesManager service_manag;
    // Operations
  public:
    Server ();
    int run ();
  };

};

#endif
