// Generated by dia2code
#ifndef SERVER__UTILISATEURSERVICE__H
#define SERVER__UTILISATEURSERVICE__H

#include <json/json.h>
namespace server {
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"

namespace server {

  /// class UtilisateurService - 
  class UtilisateurService : public server::AbstractService {
    // Operations
  public:
    UtilisateurService ();
    HttpStatus put (Json::Value& out, const Json::Value& in);
    HttpStatus remove (int id);
  };

};

#endif
