# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevipole/Documents/IS/plt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevipole/Documents/IS/plt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevipole/Documents/IS/plt/CMakeFiles /home/kevipole/Documents/IS/plt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevipole/Documents/IS/plt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/state/Acces.o: src/state/Acces.cpp.o

.PHONY : src/state/Acces.o

# target to build an object file
src/state/Acces.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Acces.cpp.o
.PHONY : src/state/Acces.cpp.o

src/state/Acces.i: src/state/Acces.cpp.i

.PHONY : src/state/Acces.i

# target to preprocess a source file
src/state/Acces.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Acces.cpp.i
.PHONY : src/state/Acces.cpp.i

src/state/Acces.s: src/state/Acces.cpp.s

.PHONY : src/state/Acces.s

# target to generate assembly for a file
src/state/Acces.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Acces.cpp.s
.PHONY : src/state/Acces.cpp.s

src/state/AccesAlloc.o: src/state/AccesAlloc.cpp.o

.PHONY : src/state/AccesAlloc.o

# target to build an object file
src/state/AccesAlloc.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/AccesAlloc.cpp.o
.PHONY : src/state/AccesAlloc.cpp.o

src/state/AccesAlloc.i: src/state/AccesAlloc.cpp.i

.PHONY : src/state/AccesAlloc.i

# target to preprocess a source file
src/state/AccesAlloc.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/AccesAlloc.cpp.i
.PHONY : src/state/AccesAlloc.cpp.i

src/state/AccesAlloc.s: src/state/AccesAlloc.cpp.s

.PHONY : src/state/AccesAlloc.s

# target to generate assembly for a file
src/state/AccesAlloc.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/AccesAlloc.cpp.s
.PHONY : src/state/AccesAlloc.cpp.s

src/state/Attaque.o: src/state/Attaque.cpp.o

.PHONY : src/state/Attaque.o

# target to build an object file
src/state/Attaque.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Attaque.cpp.o
.PHONY : src/state/Attaque.cpp.o

src/state/Attaque.i: src/state/Attaque.cpp.i

.PHONY : src/state/Attaque.i

# target to preprocess a source file
src/state/Attaque.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Attaque.cpp.i
.PHONY : src/state/Attaque.cpp.i

src/state/Attaque.s: src/state/Attaque.cpp.s

.PHONY : src/state/Attaque.s

# target to generate assembly for a file
src/state/Attaque.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Attaque.cpp.s
.PHONY : src/state/Attaque.cpp.s

src/state/Combat.o: src/state/Combat.cpp.o

.PHONY : src/state/Combat.o

# target to build an object file
src/state/Combat.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Combat.cpp.o
.PHONY : src/state/Combat.cpp.o

src/state/Combat.i: src/state/Combat.cpp.i

.PHONY : src/state/Combat.i

# target to preprocess a source file
src/state/Combat.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Combat.cpp.i
.PHONY : src/state/Combat.cpp.i

src/state/Combat.s: src/state/Combat.cpp.s

.PHONY : src/state/Combat.s

# target to generate assembly for a file
src/state/Combat.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Combat.cpp.s
.PHONY : src/state/Combat.cpp.s

src/state/Element.o: src/state/Element.cpp.o

.PHONY : src/state/Element.o

# target to build an object file
src/state/Element.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Element.cpp.o
.PHONY : src/state/Element.cpp.o

src/state/Element.i: src/state/Element.cpp.i

.PHONY : src/state/Element.i

# target to preprocess a source file
src/state/Element.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Element.cpp.i
.PHONY : src/state/Element.cpp.i

src/state/Element.s: src/state/Element.cpp.s

.PHONY : src/state/Element.s

# target to generate assembly for a file
src/state/Element.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Element.cpp.s
.PHONY : src/state/Element.cpp.s

src/state/ElementFactory.o: src/state/ElementFactory.cpp.o

.PHONY : src/state/ElementFactory.o

# target to build an object file
src/state/ElementFactory.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementFactory.cpp.o
.PHONY : src/state/ElementFactory.cpp.o

src/state/ElementFactory.i: src/state/ElementFactory.cpp.i

.PHONY : src/state/ElementFactory.i

# target to preprocess a source file
src/state/ElementFactory.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementFactory.cpp.i
.PHONY : src/state/ElementFactory.cpp.i

src/state/ElementFactory.s: src/state/ElementFactory.cpp.s

.PHONY : src/state/ElementFactory.s

# target to generate assembly for a file
src/state/ElementFactory.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ElementFactory.cpp.s
.PHONY : src/state/ElementFactory.cpp.s

src/state/Etat.o: src/state/Etat.cpp.o

.PHONY : src/state/Etat.o

# target to build an object file
src/state/Etat.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Etat.cpp.o
.PHONY : src/state/Etat.cpp.o

src/state/Etat.i: src/state/Etat.cpp.i

.PHONY : src/state/Etat.i

# target to preprocess a source file
src/state/Etat.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Etat.cpp.i
.PHONY : src/state/Etat.cpp.i

src/state/Etat.s: src/state/Etat.cpp.s

.PHONY : src/state/Etat.s

# target to generate assembly for a file
src/state/Etat.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Etat.cpp.s
.PHONY : src/state/Etat.cpp.s

src/state/GrilleElements.o: src/state/GrilleElements.cpp.o

.PHONY : src/state/GrilleElements.o

# target to build an object file
src/state/GrilleElements.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/GrilleElements.cpp.o
.PHONY : src/state/GrilleElements.cpp.o

src/state/GrilleElements.i: src/state/GrilleElements.cpp.i

.PHONY : src/state/GrilleElements.i

# target to preprocess a source file
src/state/GrilleElements.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/GrilleElements.cpp.i
.PHONY : src/state/GrilleElements.cpp.i

src/state/GrilleElements.s: src/state/GrilleElements.cpp.s

.PHONY : src/state/GrilleElements.s

# target to generate assembly for a file
src/state/GrilleElements.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/GrilleElements.cpp.s
.PHONY : src/state/GrilleElements.cpp.s

src/state/Heros.o: src/state/Heros.cpp.o

.PHONY : src/state/Heros.o

# target to build an object file
src/state/Heros.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Heros.cpp.o
.PHONY : src/state/Heros.cpp.o

src/state/Heros.i: src/state/Heros.cpp.i

.PHONY : src/state/Heros.i

# target to preprocess a source file
src/state/Heros.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Heros.cpp.i
.PHONY : src/state/Heros.cpp.i

src/state/Heros.s: src/state/Heros.cpp.s

.PHONY : src/state/Heros.s

# target to generate assembly for a file
src/state/Heros.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Heros.cpp.s
.PHONY : src/state/Heros.cpp.s

src/state/HerosAlloc.o: src/state/HerosAlloc.cpp.o

.PHONY : src/state/HerosAlloc.o

# target to build an object file
src/state/HerosAlloc.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/HerosAlloc.cpp.o
.PHONY : src/state/HerosAlloc.cpp.o

src/state/HerosAlloc.i: src/state/HerosAlloc.cpp.i

.PHONY : src/state/HerosAlloc.i

# target to preprocess a source file
src/state/HerosAlloc.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/HerosAlloc.cpp.i
.PHONY : src/state/HerosAlloc.cpp.i

src/state/HerosAlloc.s: src/state/HerosAlloc.cpp.s

.PHONY : src/state/HerosAlloc.s

# target to generate assembly for a file
src/state/HerosAlloc.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/HerosAlloc.cpp.s
.PHONY : src/state/HerosAlloc.cpp.s

src/state/IElementAlloc.o: src/state/IElementAlloc.cpp.o

.PHONY : src/state/IElementAlloc.o

# target to build an object file
src/state/IElementAlloc.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/IElementAlloc.cpp.o
.PHONY : src/state/IElementAlloc.cpp.o

src/state/IElementAlloc.i: src/state/IElementAlloc.cpp.i

.PHONY : src/state/IElementAlloc.i

# target to preprocess a source file
src/state/IElementAlloc.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/IElementAlloc.cpp.i
.PHONY : src/state/IElementAlloc.cpp.i

src/state/IElementAlloc.s: src/state/IElementAlloc.cpp.s

.PHONY : src/state/IElementAlloc.s

# target to generate assembly for a file
src/state/IElementAlloc.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/IElementAlloc.cpp.s
.PHONY : src/state/IElementAlloc.cpp.s

src/state/ListeElements.o: src/state/ListeElements.cpp.o

.PHONY : src/state/ListeElements.o

# target to build an object file
src/state/ListeElements.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ListeElements.cpp.o
.PHONY : src/state/ListeElements.cpp.o

src/state/ListeElements.i: src/state/ListeElements.cpp.i

.PHONY : src/state/ListeElements.i

# target to preprocess a source file
src/state/ListeElements.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ListeElements.cpp.i
.PHONY : src/state/ListeElements.cpp.i

src/state/ListeElements.s: src/state/ListeElements.cpp.s

.PHONY : src/state/ListeElements.s

# target to generate assembly for a file
src/state/ListeElements.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/ListeElements.cpp.s
.PHONY : src/state/ListeElements.cpp.s

src/state/Mobile.o: src/state/Mobile.cpp.o

.PHONY : src/state/Mobile.o

# target to build an object file
src/state/Mobile.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Mobile.cpp.o
.PHONY : src/state/Mobile.cpp.o

src/state/Mobile.i: src/state/Mobile.cpp.i

.PHONY : src/state/Mobile.i

# target to preprocess a source file
src/state/Mobile.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Mobile.cpp.i
.PHONY : src/state/Mobile.cpp.i

src/state/Mobile.s: src/state/Mobile.cpp.s

.PHONY : src/state/Mobile.s

# target to generate assembly for a file
src/state/Mobile.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Mobile.cpp.s
.PHONY : src/state/Mobile.cpp.s

src/state/Monstre.o: src/state/Monstre.cpp.o

.PHONY : src/state/Monstre.o

# target to build an object file
src/state/Monstre.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Monstre.cpp.o
.PHONY : src/state/Monstre.cpp.o

src/state/Monstre.i: src/state/Monstre.cpp.i

.PHONY : src/state/Monstre.i

# target to preprocess a source file
src/state/Monstre.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Monstre.cpp.i
.PHONY : src/state/Monstre.cpp.i

src/state/Monstre.s: src/state/Monstre.cpp.s

.PHONY : src/state/Monstre.s

# target to generate assembly for a file
src/state/Monstre.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Monstre.cpp.s
.PHONY : src/state/Monstre.cpp.s

src/state/MonstreAlloc.o: src/state/MonstreAlloc.cpp.o

.PHONY : src/state/MonstreAlloc.o

# target to build an object file
src/state/MonstreAlloc.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/MonstreAlloc.cpp.o
.PHONY : src/state/MonstreAlloc.cpp.o

src/state/MonstreAlloc.i: src/state/MonstreAlloc.cpp.i

.PHONY : src/state/MonstreAlloc.i

# target to preprocess a source file
src/state/MonstreAlloc.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/MonstreAlloc.cpp.i
.PHONY : src/state/MonstreAlloc.cpp.i

src/state/MonstreAlloc.s: src/state/MonstreAlloc.cpp.s

.PHONY : src/state/MonstreAlloc.s

# target to generate assembly for a file
src/state/MonstreAlloc.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/MonstreAlloc.cpp.s
.PHONY : src/state/MonstreAlloc.cpp.s

src/state/Personnage.o: src/state/Personnage.cpp.o

.PHONY : src/state/Personnage.o

# target to build an object file
src/state/Personnage.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Personnage.cpp.o
.PHONY : src/state/Personnage.cpp.o

src/state/Personnage.i: src/state/Personnage.cpp.i

.PHONY : src/state/Personnage.i

# target to preprocess a source file
src/state/Personnage.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Personnage.cpp.i
.PHONY : src/state/Personnage.cpp.i

src/state/Personnage.s: src/state/Personnage.cpp.s

.PHONY : src/state/Personnage.s

# target to generate assembly for a file
src/state/Personnage.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Personnage.cpp.s
.PHONY : src/state/Personnage.cpp.s

src/state/Statique.o: src/state/Statique.cpp.o

.PHONY : src/state/Statique.o

# target to build an object file
src/state/Statique.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Statique.cpp.o
.PHONY : src/state/Statique.cpp.o

src/state/Statique.i: src/state/Statique.cpp.i

.PHONY : src/state/Statique.i

# target to preprocess a source file
src/state/Statique.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Statique.cpp.i
.PHONY : src/state/Statique.cpp.i

src/state/Statique.s: src/state/Statique.cpp.s

.PHONY : src/state/Statique.s

# target to generate assembly for a file
src/state/Statique.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Statique.cpp.s
.PHONY : src/state/Statique.cpp.s

src/state/Vide.o: src/state/Vide.cpp.o

.PHONY : src/state/Vide.o

# target to build an object file
src/state/Vide.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Vide.cpp.o
.PHONY : src/state/Vide.cpp.o

src/state/Vide.i: src/state/Vide.cpp.i

.PHONY : src/state/Vide.i

# target to preprocess a source file
src/state/Vide.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Vide.cpp.i
.PHONY : src/state/Vide.cpp.i

src/state/Vide.s: src/state/Vide.cpp.s

.PHONY : src/state/Vide.s

# target to generate assembly for a file
src/state/Vide.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Vide.cpp.s
.PHONY : src/state/Vide.cpp.s

src/state/VideAlloc.o: src/state/VideAlloc.cpp.o

.PHONY : src/state/VideAlloc.o

# target to build an object file
src/state/VideAlloc.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/VideAlloc.cpp.o
.PHONY : src/state/VideAlloc.cpp.o

src/state/VideAlloc.i: src/state/VideAlloc.cpp.i

.PHONY : src/state/VideAlloc.i

# target to preprocess a source file
src/state/VideAlloc.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/VideAlloc.cpp.i
.PHONY : src/state/VideAlloc.cpp.i

src/state/VideAlloc.s: src/state/VideAlloc.cpp.s

.PHONY : src/state/VideAlloc.s

# target to generate assembly for a file
src/state/VideAlloc.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/VideAlloc.cpp.s
.PHONY : src/state/VideAlloc.cpp.s

src/state/Visiteur.o: src/state/Visiteur.cpp.o

.PHONY : src/state/Visiteur.o

# target to build an object file
src/state/Visiteur.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Visiteur.cpp.o
.PHONY : src/state/Visiteur.cpp.o

src/state/Visiteur.i: src/state/Visiteur.cpp.i

.PHONY : src/state/Visiteur.i

# target to preprocess a source file
src/state/Visiteur.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Visiteur.cpp.i
.PHONY : src/state/Visiteur.cpp.i

src/state/Visiteur.s: src/state/Visiteur.cpp.s

.PHONY : src/state/Visiteur.s

# target to generate assembly for a file
src/state/Visiteur.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/state/Visiteur.cpp.s
.PHONY : src/state/Visiteur.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/state/Acces.o"
	@echo "... src/state/Acces.i"
	@echo "... src/state/Acces.s"
	@echo "... src/state/AccesAlloc.o"
	@echo "... src/state/AccesAlloc.i"
	@echo "... src/state/AccesAlloc.s"
	@echo "... src/state/Attaque.o"
	@echo "... src/state/Attaque.i"
	@echo "... src/state/Attaque.s"
	@echo "... src/state/Combat.o"
	@echo "... src/state/Combat.i"
	@echo "... src/state/Combat.s"
	@echo "... src/state/Element.o"
	@echo "... src/state/Element.i"
	@echo "... src/state/Element.s"
	@echo "... src/state/ElementFactory.o"
	@echo "... src/state/ElementFactory.i"
	@echo "... src/state/ElementFactory.s"
	@echo "... src/state/Etat.o"
	@echo "... src/state/Etat.i"
	@echo "... src/state/Etat.s"
	@echo "... src/state/GrilleElements.o"
	@echo "... src/state/GrilleElements.i"
	@echo "... src/state/GrilleElements.s"
	@echo "... src/state/Heros.o"
	@echo "... src/state/Heros.i"
	@echo "... src/state/Heros.s"
	@echo "... src/state/HerosAlloc.o"
	@echo "... src/state/HerosAlloc.i"
	@echo "... src/state/HerosAlloc.s"
	@echo "... src/state/IElementAlloc.o"
	@echo "... src/state/IElementAlloc.i"
	@echo "... src/state/IElementAlloc.s"
	@echo "... src/state/ListeElements.o"
	@echo "... src/state/ListeElements.i"
	@echo "... src/state/ListeElements.s"
	@echo "... src/state/Mobile.o"
	@echo "... src/state/Mobile.i"
	@echo "... src/state/Mobile.s"
	@echo "... src/state/Monstre.o"
	@echo "... src/state/Monstre.i"
	@echo "... src/state/Monstre.s"
	@echo "... src/state/MonstreAlloc.o"
	@echo "... src/state/MonstreAlloc.i"
	@echo "... src/state/MonstreAlloc.s"
	@echo "... src/state/Personnage.o"
	@echo "... src/state/Personnage.i"
	@echo "... src/state/Personnage.s"
	@echo "... src/state/Statique.o"
	@echo "... src/state/Statique.i"
	@echo "... src/state/Statique.s"
	@echo "... src/state/Vide.o"
	@echo "... src/state/Vide.i"
	@echo "... src/state/Vide.s"
	@echo "... src/state/VideAlloc.o"
	@echo "... src/state/VideAlloc.i"
	@echo "... src/state/VideAlloc.s"
	@echo "... src/state/Visiteur.o"
	@echo "... src/state/Visiteur.i"
	@echo "... src/state/Visiteur.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

