// Generated by dia2code
#ifndef ENGINE__ACTION__H
#define ENGINE__ACTION__H

#include "../state.h"
#include <vector>

namespace engine {
  class Regles;
};
namespace state {
  class Etat;
}

#include "Regles.h"

namespace engine {

  /// class Action - 
  class Action {
    // Associations
    // Attributes
  protected:
    Regles regles;
    // Operations
  public:
    virtual void run (state::Etat* e, std::vector<int> params) = 0;
  };

};

#endif
