// Generated by dia2code
#ifndef ENGINE__ATTAQUECAC__H
#define ENGINE__ATTAQUECAC__H

#include "../state.h"
#include <vector>

namespace state {
  class Etat;
};
namespace engine {
  class Attaquer;
}

#include "Attaquer.h"

namespace engine {

  /// class AttaqueCaC - 
  class AttaqueCaC : public engine::Attaquer {
    // Operations
  public:
    void run (state::Etat* e, std::vector<int> params);
  };

};

#endif
