// Generated by dia2code
#ifndef ENGINE__COMMANDE__H
#define ENGINE__COMMANDE__H

#include "../state.h"
#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <string>
#include <vector>

namespace state {
  class Etat;
};
namespace engine {
  class ListeCommandes;
  class Action;
}

#include "ListeCommandes.h"
#include "Action.h"

namespace engine {

  /// class Commande - 
  class Commande {
    // Associations
    // Operations
  public:
    Commande (state::Etat* e, sf::Time t, std::string cmd, int id, std::vector<int> params);
    ~Commande ();
  };

};

#endif
