// Generated by dia2code
#ifndef ENGINE__COMMANDE__H
#define ENGINE__COMMANDE__H

#include <map>
#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include "../state.h"

namespace state {
  class Etat;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class Commande - 
  class Commande {
    // Associations
    // Attributes
  protected:
    std::map<char,Action*> mmap;
    sf::Clock cl;
    // Operations
  public:
    Commande (sf::Event event, state::Etat* e, sf::Clock cl);
    ~Commande ();
    int const getSize ();
  };

};

#endif
