// Generated by dia2code
#ifndef ENGINE__LISTECOMMANDES__H
#define ENGINE__LISTECOMMANDES__H

#include <vector>
#include <mutex>

namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class ListeCommandes - 
  class ListeCommandes {
    // Attributes
  public:
    std::vector<Commande> commandes;
    std::vector<Commande> commandes_buf;
    std::mutex mut_buf;
    // Operations
  public:
    void Ajouter (Commande cmd);
    void ToutExecuter ();
  };

};

#endif
