// Generated by dia2code
#ifndef ENGINE__REGLES__H
#define ENGINE__REGLES__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>
#include <vector>

namespace state {
  class Etat;
}

#include "state/Etat.h"

namespace engine {

  /// class Regles - 
  class Regles {
    // Operations
  public:
    bool peutDeplacer (state::Etat* e, int id, int newX, int newY);
    bool peutEntrerCombat (state::Etat* e, int id);
    bool peutChangerMap (state::Etat* e, int id);
    bool peutQuitterCombat (state::Etat* e);
    bool peutAttaquer (state::Etat* e, int id);
    bool doitPasserTour (state::Etat* e, int id, sf::Time t);
    bool peutAccederMenu (state::Etat* e);
    bool peutAccederInfoPerso (state::Etat* e);
    bool peutAugmenterNiv (state::Etat* e, int id);
    int augmenterPM (state::Etat* e, int id);
    int augmenterPA (state::Etat* e, int id);
    int augmenterPV (state::Etat* e, int id);
    int augmenterForce (state::Etat* e, int id);
    std::vector<state::Personnage*> defMonstreCarte (state::Etat* e);
    int defCarteSuiv (state::Etat* e, int id);
  };

};

#endif
