// Generated by dia2code
#ifndef RENDER__CERTEXTE__H
#define RENDER__CERTEXTE__H

#include <SFML/Graphics.hpp>

namespace render {

  /// class CerTexte - 
  class CerTexte {
    // Attributes
  public:
    sf::Text texte;
    sf::CircleShape cercle;
    sf::Font font;
    // Operations
  public:
    void ChangeTexte (const sf::String& txt);
    CerTexte ();
    ~CerTexte ();
  };

};

#endif
