// Generated by dia2code
#ifndef RENDER__CMDRENDU__H
#define RENDER__CMDRENDU__H

#include "../state.h"
#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>

namespace state {
  class Etat;
}

namespace render {

  /// class cmdRendu - 
  class cmdRendu {
    // Operations
  public:
    cmdRendu (state::Etat* e, char typeChang, sf::Time t);
  };

};

#endif
