// Generated by dia2code
#ifndef RENDER__CMDRENDU__H
#define RENDER__CMDRENDU__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>

namespace state {
  class Etat;
}

namespace render {

  /// class cmdRendu - 
  class cmdRendu {
    // Attributes
  public:
    state::Etat * e;
    char tc;
    sf::Time t;
    // Operations
  public:
    cmdRendu (state::Etat* ne, char typeChang, sf::Time nt);
    state::Etat * getEtat ();
    sf::Time getTime ();
    char getTC ();
  };

};

#endif
