// Generated by dia2code
#ifndef RENDER__OBSERVER__H
#define RENDER__OBSERVER__H

#include <../state.h>

namespace state {
  class Etat;
}

namespace render {

  /// class Observer - 
  class Observer {
    // Operations
  public:
    virtual void run (state::Etat* e, char typechang, int id) = 0;
  };

};

#endif
