// Generated by dia2code
#ifndef RENDER__OBSERVER__H
#define RENDER__OBSERVER__H


namespace render {

  /// class Observer - 
  class Observer {
    // Operations
  public:
    virtual void run (etat* e, char typechang, int id) = 0;
  };

};

#endif
