// Generated by dia2code
#ifndef RENDER__RENDUTYPE__H
#define RENDER__RENDUTYPE__H

#include <vector>
#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>

namespace render {

  /// class RenduType - 
  class RenduType {
    // Attributes
  public:
    std::vector<sf::Sprite> sprites;
    std::vector<sf::Texture> textures;
    // Operations
  public:
    RenduType ();
    ~RenduType ();
  };

};

#endif
