// Generated by dia2code
#ifndef RENDER__RENDU__H
#define RENDER__RENDU__H

#include <SFML/Graphics.hpp>
#include "../state.h"

namespace render {
  class RenduGrille;
  class RenduPerso;
  class RenduCombat;
};
namespace state {
  class Etat;
}

#include "RenduGrille.h"
#include "RenduPerso.h"
#include "RenduCombat.h"

namespace render {

  /// class Rendu - 
  class Rendu {
    // Associations
    // Attributes
  public:
    RenduGrille rg;
    RenduPerso rp;
    RenduCombat rc;
    sf::Music son;
    sf::RenderWindow& sw;
     sf::Clock&;
    // Operations
  public:
    void run (state::Etat* e, char typeChang, int id);
    Rendu (sf::RenderWindow& sw, sf::Clock& cl);
  };

};

#endif
