// Generated by dia2code
#ifndef RENDER__RENDUGRILLE__H
#define RENDER__RENDUGRILLE__H

#include <SFML/Graphics.hpp>
#include "../state.h"

namespace render {
  class RenduType;
};
namespace state {
  class Etat;
}

#include "RenduType.h"

namespace render {

  /// class RenduGrille - 
  class RenduGrille {
    // Attributes
  public:
    RenduType Grille;
    // Operations
  public:
    void dessin (sf::RenderWindow& w, state::Etat* e, int id);
    RenduGrille ();
    ~RenduGrille ();
  };

};

#endif
