// Generated by dia2code
#ifndef RENDER__RENDUPERSO__H
#define RENDER__RENDUPERSO__H

#include <SFML/Graphics.hpp>

namespace render {
  class RenduType;
}

#include "RenduType.h"

namespace render {

  /// class RenduPerso - 
  class RenduPerso {
    // Attributes
  public:
    RenduType Heros1;
    RenduType Heros2;
    RenduType Monstre1;
    RenduType Monstre2;
    RenduType Monstre3;
    RenduType Monstre4;
    RenduType Monstre5;
    // Operations
  public:
    void dessin (sf::renderWindow w, etat* e, int id);
    RenduPerso ();
    ~RenduPerso ();
  };

};

#endif
