// Generated by dia2code
#ifndef RENDER__RENDUGRILLE__H
#define RENDER__RENDUGRILLE__H

#include <SFML/Graphics.hpp>
#include "../state.h"
#include <string>

namespace state {
  class Etat;
}

namespace render {

  /// class RenduGrille - 
  class RenduGrille {
    // Attributes
  private:
    sf::VertexArray m_vertices;
    sf::Texture m_tileset;
  protected:
    const int level[];
    // Operations
  public:
    void dessin (sf::RenderTarget&  target, state::Etat* e);
    RenduGrille ();
    ~RenduGrille ();
  private:
    bool charger (const std::string& tileset, sf::Vector2u  tileSize, const int*  tiles, unsigned int  width, unsigned int  height);
  };

};

#endif
