// Generated by dia2code
#ifndef RENDER__RENDU__H
#define RENDER__RENDU__H

#include <vector>
#include <mutex>
#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>

namespace render {
  class RenduGrille;
  class RenduPerso;
  class cmdRendu;
};
namespace state {
  class Etat;
  class Observer;
}

#include "RenduGrille.h"
#include "RenduPerso.h"
#include "cmdRendu.h"
#include "state/Observer.h"

namespace render {

  /// class Rendu - 
  class Rendu : public state::Observer {
    // Associations
    // Attributes
  public:
    RenduGrille rg;
    RenduPerso rp;
    std::vector<cmdRendu> cmd_buf;
    std::vector<cmdRendu> cmd;
    std::mutex mut_cmdbuf;
    // Operations
  public:
    Rendu ();
    void run (state::Etat* e, sf::RenderWindow& sw, sf::Time cl, sf::RenderStates rs);
    void maj (state::Etat * e, char typechang, sf::Time t);
  };

};

#endif
