// Generated by dia2code
#ifndef RENDER__RENDUPERSO__H
#define RENDER__RENDUPERSO__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include "../state.h"

namespace state {
  class Etat;
};
namespace render {
  class Parseur;
}

#include "Parseur.h"

namespace render {

  /// class RenduPerso - 
  class RenduPerso {
    // Attributes
  public:
    sf::VertexArray vertices;
    sf::Texture tileset;
    // Operations
  public:
    void dessin (sf::RenderWindow& w, state::Etat* e, int id, sf::Clock& cl, sf::RenderStates rs);
    RenduPerso ();
    ~RenduPerso ();
  };

};

#endif
