// Generated by dia2code
#ifndef RENDER__RENDU__H
#define RENDER__RENDU__H

#include <SFML/Graphics.hpp>

namespace render {
  class RenduGrille;
  class RenduPerso;
  class RenduCombat;
  class Observer;
}

#include "RenduGrille.h"
#include "RenduPerso.h"
#include "RenduCombat.h"
#include "Observer.h"

namespace render {

  /// class Rendu - 
  class Rendu : public render::Observer {
    // Associations
    // Attributes
  public:
    RenduGrille rg;
    RenduPerso rp;
    RenduBackground rb;
    RenduCombat rc;
    sf::Music son;
    // Operations
  public:
    void run (etat* e, char typeChang, int id);
  };

};

#endif
