// Generated by dia2code
#ifndef IA__IA__H
#define IA__IA__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>

namespace state {
  class Etat;
};
namespace engine {
  class Commande;
}

#include "engine/Commande.h"

namespace ia {

  /// class IA - 
  class IA {
    // Attributes
  protected:
    state::Etat* etat;
    // Operations
  public:
    IA (state::Etat* etat);
    IA ();
    ~IA ();
    virtual engine::Commande exec_cmd (int id, sf::Time time) = 0;
  };

};

#endif
