// Generated by dia2code
#ifndef IA__IACOMBAT__H
#define IA__IACOMBAT__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>

namespace ia {
  class IAheuristic;
};
namespace state {
  class Etat;
};
namespace engine {
  class Commande;
};
namespace ia {
  class IA;
}

#include "IAheuristic.h"
#include "engine/Commande.h"
#include "IA.h"

namespace ia {

  /// class IAcombat - 
  class IAcombat : public ia::IA {
    // Associations
    // Attributes
  public:
    IAheuristic strat;
    // Operations
  public:
    IAcombat ();
    IAcombat (state::Etat* etat);
    IAheuristic getIAheuristic ();
    engine::Commande exec_cmd (int id, sf::Time time);
  };

};

#endif
