// Generated by dia2code
#ifndef IA__IAHEURISTIC__H
#define IA__IAHEURISTIC__H

#include "../state.h"
#include <vector>

namespace state {
  class Personnage;
  class Etat;
}

namespace ia {

  /// class IAheuristic - 
  class IAheuristic {
    // Operations
  public:
    state::Personnage* cible (int id, state::Etat* etat);
    std::vector< int > posCible (state::Etat* etat, int id, state::Personnage* ennemi);
    bool attaqueCible (state::Etat* etat, int id, state::Personnage* ennemi);
  };

};

#endif
