// Generated by dia2code
#ifndef IA__IAHEURISTIC__H
#define IA__IAHEURISTIC__H

#include "../state.h"

namespace state {
  class Personnage;
}

namespace ia {

  /// class IAheuristic - 
  class IAheuristic {
    // Operations
  public:
    state::Personnage& cible ();
  };

};

#endif
