// Generated by dia2code
#ifndef IA__IAHEURISTIC__H
#define IA__IAHEURISTIC__H

#include "../state.h"
#include <vector>

namespace state {
  class Personnage;
}

namespace ia {

  /// class IAheuristic - 
  class IAheuristic {
    // Operations
  public:
    state::Personnage* cible (std::vector<state::Personnage* > ennemis);
  };

};

#endif
