// Generated by dia2code
#ifndef IA__IAMINIMALE__H
#define IA__IAMINIMALE__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>

namespace state {
  class Etat;
};
namespace ia {
  class IA;
}

#include "IA.h"

namespace ia {

  /// class IAminimale - 
  class IAminimale : public ia::IA {
    // Operations
  public:
    IAminimale (state::Etat* etat);
    ~IAminimale ();
    virtual engine::Commande exec_cmd (int id, sf::Time time);
  };

};

#endif
