// Generated by dia2code
#ifndef IA__MINMAXIA__H
#define IA__MINMAXIA__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>

namespace ia {
  class Arbre;
};
namespace engine {
  class Commande;
};
namespace ia {
  class IA;
}

#include "Arbre.h"
#include "engine/Commande.h"
#include "IA.h"

namespace ia {

  /// class MinMaxIA - 
  class MinMaxIA : public ia::IA {
    // Associations
    // Attributes
  protected:
    Arbre tmp_arbre;
    // Operations
  public:
    MinMaxIA ();
    /// 	
    /// @param id		(???) 
    /// @param time		(???) 
    engine::Commande exec_cmd (int id, sf::Time time);
  };

};

#endif
