// Generated by dia2code
#ifndef STATE__ACCES__H
#define STATE__ACCES__H


namespace state {
  class IVisiteur;
  class Statique;
}

#include "TypeID.h"
#include "Statique.h"

namespace state {

  /// class Acces - 
  class Acces : public state::Statique {
    // Operations
  public:
    Acces (int i, int j);
    bool isAcces ();
    TypeID getTypeID ();
    void accepte (IVisiteur& v);
  };

};

#endif
