// Generated by dia2code
#ifndef ACCESALLOC__H
#define ACCESALLOC__H

/// class AccesAlloc - 
class AccesAlloc : public IElementAlloc {
  // Attributes
protected:
  int id;
  // Operations
public:
  AccesAlloc (int id);
  Element* newInstance ();
};

#endif
