// Generated by dia2code
#ifndef ACCES__H
#define ACCES__H

/// class Acces - 
class Acces : public Statique {
  // Operations
public:
  Acces (int i, int j);
  bool isAcces ();
  TypeID getTypeID ();
  void accepte (IVisiteur& v);
};

#endif
