// Generated by dia2code
#ifndef ATTAQUE__H
#define ATTAQUE__H

/// class Attaque - 
class Attaque {
  // Associations
  // Attributes
protected:
  TypeAttaque typeAttaque;
  int degat;
  int coutPA;
  // Operations
public:
  Attaque ();
  ~Attaque ();
  int getCoutPA ();
  void setCoutPA (int i);
};

#endif
