// Generated by dia2code
#ifndef STATE__ATTAQUE__H
#define STATE__ATTAQUE__H


#include "TypeAttaque.h"

namespace state {

  /// class Attaque - 
  class Attaque {
    // Associations
    // Attributes
  protected:
    TypeAttaque typeAttaque;
    int degat;
    int coutPA;
    // Operations
  public:
    Attaque ();
    ~Attaque ();
    int getCoutPA ();
    void setCoutPA (int i);
  };

};

#endif
