// Generated by dia2code
#ifndef STATE__DIRECTION__H
#define STATE__DIRECTION__H


namespace state {

  enum Direction {
    NORD     = 1,
    SUD     = 2,
    EST     = 3,
    OUEST     = 4,
    NONE     = 0
  };

};

#endif
