// Generated by dia2code
#ifndef STATE__ELEMENTFACTORY__H
#define STATE__ELEMENTFACTORY__H

#include <map>

namespace state {
  class Element;
  class IElementAlloc;
}

#include "IElementAlloc.h"

namespace state {

  /// class ElementFactory - 
  class ElementFactory {
    // Associations
    // Attributes
  public:
    int id;
  protected:
    std::map<char, IElementAlloc*> liste;
    // Operations
  public:
    ElementFactory ();
    ~ElementFactory ();
    Element* newInstance (char id);
    void registerType (char cid, IElementAlloc& a);
  };

};

#endif
