// Generated by dia2code
#ifndef ELEMENTFACTORY__H
#define ELEMENTFACTORY__H

/// class ElementFactory - 
class ElementFactory {
  // Associations
  // Attributes
protected:
  std::map<char, IElementAlloc*> liste;
  static int id;
  // Operations
public:
  ElementFactory ();
  Element* newInstance (char id);
  void registerType (char id, IElementAlloc& a);
};

#endif
