// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class IVisiteur;
  class IAccepteVisite;
}

#include "TypeID.h"
#include "IAccepteVisite.h"

namespace state {

  /// class Element - 
  class Element : public state::IAccepteVisite {
    // Associations
    // Attributes
  protected:
    int x;
    int y;
    TypeID typeID;
    int elemID;
    // Operations
  public:
    Element ();
    ~Element ();
    virtual TypeID getTypeID () = 0;
    virtual void accepte (IVisiteur& v ) = 0;
    int getX ();
    int getY ();
    void setX (int const x);
    void setY (int const y);
    int getElemID ();
    void setElemID (int i);
  };

};

#endif
