// Generated by dia2code
#ifndef STATE__HEROS__H
#define STATE__HEROS__H


namespace state {
  class IVisiteur;
  class Personnage;
}

#include "TypePersonnage.h"
#include "TypeID.h"
#include "Personnage.h"

namespace state {

  /// class Heros - 
  class Heros : public state::Personnage {
    // Attributes
  protected:
    int experience;
    // Operations
  public:
    Heros (int i, int j, int exp);
    Heros (int nv, TypePersonnage type);
    bool isJoueur ();
    TypeID getTypeID ();
    int const getExp ();
    void setExp (int const Exp);
    void accepte (IVisiteur& v);
  };

};

#endif
