// Generated by dia2code
#ifndef STATE__HEROSALLOC__H
#define STATE__HEROSALLOC__H


namespace state {
  class Element;
  class IElementAlloc;
}

#include "IElementAlloc.h"

namespace state {

  /// class HerosAlloc - 
  class HerosAlloc : public state::IElementAlloc {
    // Attributes
  protected:
    int id;
    // Operations
  public:
    HerosAlloc (int id);
    Element* newInstance ();
  };

};

#endif
