// Generated by dia2code
#ifndef HEROSALLOC__H
#define HEROSALLOC__H

/// class HerosAlloc - 
class HerosAlloc : public IElementAlloc {
  // Attributes
protected:
  int id;
  // Operations
public:
  HerosAlloc (int id);
  Element* newInstance ();
};

#endif
