// Generated by dia2code
#ifndef IACCEPTEVISITE__H
#define IACCEPTEVISITE__H

/// class IAccepteVisite - 
class IAccepteVisite {
  // Operations
public:
  virtual void accepte (IVisiteur& v) = 0;
};

#endif
