// Generated by dia2code
#ifndef STATE__IACCEPTEVISITE__H
#define STATE__IACCEPTEVISITE__H


namespace state {
  class IVisiteur;
}

namespace state {

  /// class IAccepteVisite - 
  class IAccepteVisite {
    // Operations
  public:
    virtual void accepte (IVisiteur& v) = 0;
  };

};

#endif
