// Generated by dia2code
#ifndef IELEMENTALLOC__H
#define IELEMENTALLOC__H

/// class IElementAlloc - 
class IElementAlloc {
  // Operations
public:
  IElementAlloc ();
  virtual Element* newInstance () = 0;
};

#endif
