// Generated by dia2code
#ifndef STATE__IELEMENTALLOC__H
#define STATE__IELEMENTALLOC__H


namespace state {
  class Element;
}

namespace state {

  /// class IElementAlloc - 
  class IElementAlloc {
    // Operations
  public:
    IElementAlloc ();
    virtual Element* newInstance () = 0;
  };

};

#endif
