// Generated by dia2code
#ifndef STATE__IVISITEUR__H
#define STATE__IVISITEUR__H


namespace state {
  class Heros;
  class Vide;
  class Acces;
  class Monstre;
}

namespace state {

  /// class IVisiteur - 
  class IVisiteur {
    // Attributes
  public:
    Heros* pHeros;
    Vide* pVide;
    Acces* pAcces;
    Monstre* pMonstre;
  protected:
    int lastype;
    // Operations
  public:
    virtual void visiter (Heros* pHeros) = 0;
    virtual void visiter (Vide* pVide) = 0;
    virtual void visiter (Acces* pAcces) = 0;
    virtual void visiter (Monstre* pMonstre) = 0;
  };

};

#endif
