// Generated by dia2code
#ifndef STATE__LISTEELEMENTS__H
#define STATE__LISTEELEMENTS__H

#include <vector>

namespace state {
  class Visiteur;
  class Etat;
  class Personnage;
  class Element;
  class ElementFactory;
  class Statique;
}

#include "Visiteur.h"
#include "ElementFactory.h"
#include "Element.h"

namespace state {

  /// class ListeElements - 
  class ListeElements {
    // Associations
    // Attributes
  public:
    Visiteur visiteur;
    Etat* etat;
    Personnage * soldatInconnu;
  protected:
    std::vector<Element*>  elements;
    ElementFactory* factory;
    // Operations
  public:
    ListeElements (Etat* etat);
    ~ListeElements ();
    int size ();
    Element* getElement (int i);
    void setElement (int  i, Element* e);
    bool const isPerso (int i, int j);
    void ajoutElement (char e);
    void ajoutElement (Element * e);
    Statique* getTile (int i);
    void clear ();
    void eraseElem (int i);
    Etat* getEtat ();
  };

};

#endif
