// Generated by dia2code
#ifndef STATE__LISTEELEMENTS__H
#define STATE__LISTEELEMENTS__H

#include <vector>

namespace state {
  class Element;
  class ElementFactory;
}

#include "ElementFactory.h"
#include "Element.h"

namespace state {

  /// class ListeElements - 
  class ListeElements {
    // Associations
    // Attributes
  protected:
    std::vector<Element*>  elements;
    ElementFactory* factory;
    // Operations
  public:
    ListeElements ();
    ~ListeElements ();
    int size ();
    Element* getElement (int i);
    void setElement (int  i, Element* e);
    bool const isPerso (int i, int j);
    void ajoutElement (Element* e);
  };

};

#endif
