// Generated by dia2code
#ifndef MOBILE__H
#define MOBILE__H

/// class Mobile - 
class Mobile : public Element {
  // Associations
  // Attributes
protected:
  bool joueur;
  Direction direction;
  int timer;
  bool  enDeplacement;
  // Operations
public:
  Mobile ();
  virtual bool isJoueur () = 0;
  virtual void accepte (IVisiteur& v) = 0;
  virtual TypeID getTypeID () = 0;
  bool const isStatic ();
  Direction getDirection ();
  void setDirection (Direction d);
  bool getEnDeplacement ();
  void setEnDeplacement (bool b);
  int getTimer ();
  void setTimer (int timer);
};

#endif
