// Generated by dia2code
#ifndef STATE__MOBILE__H
#define STATE__MOBILE__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>

namespace state {
  class IVisiteur;
  class Element;
}

#include "Direction.h"
#include "TypeID.h"
#include "Element.h"

namespace state {

  /// class Mobile - 
  class Mobile : public state::Element {
    // Associations
    // Attributes
  protected:
    bool joueur;
    Direction direction;
    sf::Time timer;
    bool  enDeplacement;
    int xObj;
    int yObj;
    // Operations
  public:
    Mobile ();
    virtual bool isJoueur () = 0;
    virtual void accepte (IVisiteur& v) = 0;
    virtual TypeID getTypeID () = 0;
    bool const isStatic ();
    Direction getDirection ();
    void setDirection (Direction d);
    bool getEnDeplacement ();
    void setEnDeplacement (bool b);
    sf::Time getTimer ();
    void setTimer (sf::Time timer);
    int const getXobj ();
    void setXobj (int x);
    int const getYobj ();
    void setYobj (int y);
  };

};

#endif
