// Generated by dia2code
#ifndef MONSTREALLOC__H
#define MONSTREALLOC__H

/// class MonstreAlloc - 
class MonstreAlloc : public IElementAlloc {
  // Attributes
protected:
  int id;
  // Operations
public:
  MonstreAlloc (int id);
  Element* newInstance ();
};

#endif
