// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace render {
  class Observer;
}

#include "render/Observer.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  public:
    std::vector<render::Observer *> observers;
    // Operations
  public:
    virtual void notifyObserver ( );
    void registerObserver (render::Observer * obs);
    virtual ~Observable ();
  };

};

#endif
