// Generated by dia2code
#ifndef PERSONNAGE__H
#define PERSONNAGE__H

/// class Personnage - 
class Personnage : public Mobile {
  // Associations
  // Attributes
protected:
  TypePersonnage typePerso;
  int force;
  int niveau;
  int ptAction;
  int ptMouvement;
  int vie;
  Attaque attaqueDistance;
  Attaque attaqueCAC;
  EtatPerso etatPerso;
  // Operations
public:
  Personnage (int  niveau, TypePersonnage type );
  ~Personnage ();
  virtual bool isJoueur () = 0;
  virtual void accepte (IVisiteur& v) = 0;
  virtual TypeID getTypeID () = 0;
  TypePersonnage getTypePersonnage ();
  int getForce ();
  int getNiveau ();
  int getPA ();
  int getPM ();
  int getVie ();
  Attaque getAttaqueDistance ();
  Attaque getAttaqueCAC ();
  EtatPerso getEtatPerso ();
  void setTypePersonnage (TypePersonnage  type);
  void setForce (int i);
  void setNiveau (int i);
  void setPA (int i);
  void setPM (int i);
  void setVie (int i);
  void setAttaqueDistance (Attaque attaqueDist);
  void setAttaqueCAC (Attaque AttaqueCorps);
  void setEtatPerso (EtatPerso etatPerso);
};

#endif
