// Generated by dia2code
#ifndef STATIQUE__H
#define STATIQUE__H

/// class Statique - 
class Statique : public Element {
  // Operations
public:
  Statique ();
  virtual bool  isAcces () = 0;
  virtual void accepte (IVisiteur& v) = 0;
  virtual TypeID getTypeID () = 0;
  bool isStatic ();
};

#endif
