// Generated by dia2code
#ifndef STATE__STATIQUE__H
#define STATE__STATIQUE__H


namespace state {
  class IVisiteur;
  class Element;
}

#include "TypeID.h"
#include "Element.h"

namespace state {

  /// class Statique - 
  class Statique : public state::Element {
    // Operations
  public:
    Statique ();
    virtual bool  isAcces () = 0;
    virtual void accepte (IVisiteur& v) = 0;
    virtual TypeID getTypeID () = 0;
    bool isStatic ();
  };

};

#endif
