// Generated by dia2code
#ifndef STATE__TYPEPERSONNAGE__H
#define STATE__TYPEPERSONNAGE__H


namespace state {

  enum TypePersonnage {
    HEROS     = 1,
    HEROINE     = 2,
    MONSTRE1     = 3,
    MONSTRE2     = 4,
    MONSTRE3     = 5,
    MONSTRE4     = 6,
    BOSS     = 7
  };

};

#endif
