// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeID {
    VIDE     = 1,
    ACCES     = 2,
    PERSO      = 3,
    MONSTRE      = 4
  };

};

#endif
