// Generated by dia2code
#ifndef VIDEALLOC__H
#define VIDEALLOC__H

/// class VideAlloc - 
class VideAlloc : public IElementAlloc {
  // Attributes
protected:
  int id;
  // Operations
public:
  VideAlloc (int id);
  Element* newInstance ();
};

#endif
