// Generated by dia2code
#ifndef STATE__VIDEALLOC__H
#define STATE__VIDEALLOC__H


namespace state {
  class Element;
  class IElementAlloc;
}

#include "IElementAlloc.h"

namespace state {

  /// class VideAlloc - 
  class VideAlloc : public state::IElementAlloc {
    // Attributes
  protected:
    int id;
    // Operations
  public:
    VideAlloc (int id);
    Element* newInstance ();
  };

};

#endif
