// Generated by dia2code
#ifndef VIDE__H
#define VIDE__H

/// class Vide - 
class Vide : public Statique {
  // Operations
public:
  Vide (int i, int j);
  bool isAcces ();
  TypeID getTypeID ();
  void accepte (IVisiteur& v);
};

#endif
