// Generated by dia2code
#ifndef VISITEUR__H
#define VISITEUR__H

/// class Visiteur - 
class Visiteur : public IVisiteur {
  // Operations
public:
  void visiter (Heros* pHeros);
  void visiter (Vide* pVide);
  void visiter (Acces* pAcces);
  void visiter (Monstre* pMonstre);
  Heros* getpHeros ();
  Monstre* getpMonstre ();
  Acces* getpAcces ();
  Vide* getpVide ();
};

#endif
