// Generated by dia2code
#ifndef STATE__VISITEUR__H
#define STATE__VISITEUR__H


namespace state {
  class Heros;
  class Vide;
  class Acces;
  class Monstre;
  class IVisiteur;
}

#include "IVisiteur.h"

namespace state {

  /// class Visiteur - 
  class Visiteur : public state::IVisiteur {
    // Operations
  public:
    void visiter (Heros* pHeros);
    void visiter (Vide* pVide);
    void visiter (Acces* pAcces);
    void visiter (Monstre* pMonstre);
    Heros* getpHeros ();
    Monstre* getpMonstre ();
    Acces* getpAcces ();
    Vide* getpVide ();
  };

};

#endif
