// Generated by dia2code
#ifndef DEPLACER__H
#define DEPLACER__H

/// class Deplacer - 
class Deplacer : public engine::Action {
  // Operations
public:
  void run (state::Etat* e, std::vector<int> params);
};

#endif
