// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/Regles.h"
#include "engine/ListeCommandes.h"
#include "engine/Action.h"
#include "engine/Commande.h"
#include "engine/Deplacer.h"
#include "engine/Attaquer.h"
#include "engine/ChangerMap.h"
#include "engine/EntrerCombat.h"
#include "engine/QuitterCombat.h"
#include "engine/PasserTour.h"
#include "engine/AttaqueDistance.h"
#include "engine/AttaqueCaC.h"
#include "engine/Moteur.h"
#endif
