// Generated by dia2code
#ifndef __IA__H
#define __IA__H

#include "ia/IA.h"
#include "ia/IAminimale.h"
#include "ia/IAheuristic.h"
#include "ia/IAcombat.h"
#include "ia/Arbre.h"
#include "ia/Noeud.h"
#endif
