// Generated by dia2code
#ifndef OBSERVABLE__H
#define OBSERVABLE__H

/// class Observable - 
class Observable : public state::Etat {
  // Associations
  // Attributes
public:
  std::vector<Observer> observers;
  // Operations
public:
  void notifyObserver ( );
  void registerObserver (Observer obs);
};

#endif
