// Generated by dia2code
#ifndef OBSERVER__H
#define OBSERVER__H

/// class Observer - 
class Observer {
  // Operations
public:
  virtual void run (state::Etat* e, char typechang, int id) = 0;
};

#endif
