// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/RenduType.h"
#include "render/RenduGrille.h"
#include "render/RenduPerso.h"
#include "render/RectTexte.h"
#include "render/CerTexte.h"
#include "render/RenduCombat.h"
#include "render/Rendu.h"
#endif
