// Generated by dia2code
#ifndef CLIENT__RECTTEXTE__H
#define CLIENT__RECTTEXTE__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>

namespace client {

  /// class RectTexte - 
  class RectTexte {
    // Attributes
  public:
    sf::Text texte;
    sf::RectangleShape rect;
    sf::Font font;
    // Operations
  public:
    void ChangeText (const sf::String& txt);
    RectTexte ();
    ~RectTexte ();
  };

};

#endif
