// Generated by dia2code
#ifndef CLIENT__RENDUCOMBAT__H
#define CLIENT__RENDUCOMBAT__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>

namespace client {
  class RectTexte;
  class CerTexte;
};
namespace state {
  class Etat;
}

#include "RectTexte.h"
#include "CerTexte.h"

namespace client {

  /// class RenduCombat - 
  class RenduCombat {
    // Associations
    // Attributes
  public:
    RectTexte iconeAttaqueDist;
    RectTexte iconeAttaqueCAC;
    RectTexte iconePA;
    RectTexte iconePM;
    CerTexte iconeVie;
    sf::CircleShape iconeTemps;
    sf::CircleShape iconeTourSuiv;
    // Operations
  public:
    void dessin (sf::RenderWindow& w, state::Etat* e, int id);
    RenduCombat ();
    ~RenduCombat ();
  };

};

#endif
